# Generated by Django 5.2.5 on 2025-08-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messengerApp', '0002_chat_speaking_partner_username_alter_chat_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='his_message_id',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
