# Generated by Django 5.2.5 on 2025-08-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messengerApp', '0003_message_his_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='his_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
